[tool.poetry]
name = "gym-brain-frontend"
version = "0.1.0"
description = "Reflex frontend for Gym Brain"
authors = ["AMarikDS"]

[tool.poetry.dependencies]
python = "^3.10"
reflex = "0.8.2"
httpx = ">=0.27.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
